FEATURES = .devcontainer/src/**/README.md

README.md: $(FEATURES)
	pandoc $? -o $@
	git add $@
	git commit -m "Automated documentation update [skip ci]"


test:
	devcontainer features test --project-folder .devcontainer --skip-autogenerated